# Generated by Django 4.2.3 on 2023-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nova poshta department'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
