# Generated by Django 4.2.3 on 2023-07-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_default_department_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_access',
            field=models.BooleanField(default=False, verbose_name='Is staff'),
        ),
    ]
