# Generated by Django 4.2.3 on 2023-07-20 13:55

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_good_stock_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Order Phone')),
                ('order_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Order E-mail')),
                ('goods_count', models.IntegerField(default=0, verbose_name='Goods count')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('active', 'Active'), ('completed', 'Completed')], max_length=20, null=True, verbose_name='Status')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.good', verbose_name='Good')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
