# Generated by Django 4.2.3 on 2023-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='stock_count',
            field=models.IntegerField(default=0, verbose_name='Stock count'),
        ),
    ]
