# Generated by Django 4.2.3 on 2023-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_characteristicstype_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='goods.characteristics'),
        ),
    ]
